apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "influxdb"
  labels:
    app: "influxdb"
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: "influxdb"
        name: "influxdb"
        app: "influxdb"
    spec:
      containers:
        - name: "influxdb"
          image: "influxdb:0.13.0" #1.0.0-beta2-alpine"
          resources:
            requests:
              memory: "8Gi"
              cpu: "2"
            limits:
              memory: "10Gi"
              cpu: "4"
          ports:
            - containerPort: 8083
            - containerPort: 8086
          imagePullPolicy: "Always"
